name: ci
on:
  push: { branches: [ main ] }
  pull_request: {}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - name: Build images
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest api
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push images
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest
