name: ci
on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Compute image name (lowercase)
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Show image name
        run: echo "$IMAGE"

      - name: Build images
        run: |
          docker build -t "$IMAGE:${GITHUB_SHA}" -t "$IMAGE:latest" api

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push images
        run: |
          docker push "$IMAGE:${GITHUB_SHA}"
          docker push "$IMAGE:latest"
